import { COLUMN_MENU_MISSING, COLUMN_MENU_SURFACE, STAFF, t } from './tourSelectors';

/** How-to guide for creating and managing view tabs (staff). */
export const TAB_GUIDES = [
  {
    id: 'guideViewTabs',
    kind: 'guide',
    version: 1,
    route: '/',
    roles: STAFF,
    icon: 'tabs',
    title: 'Create tabs',
    description: 'Create a tab per value of a column, then switch, delete and save tabs.',
    steps: [
      {
        id: 'open-column-menu',
        anchor: t('po-column-menu-trigger'),
        reveal: true,
        placement: 'bottom',
        title: 'Start from a column',
        body: 'Tabs are created from a column, for example one tab per vendor or per status. Hover the header of that column and click …',
        action: true,
        hint: 'Click the highlighted … button',
        advanceOn: { appears: COLUMN_MENU_SURFACE },
        missingText: COLUMN_MENU_MISSING,
      },
      {
        id: 'tabs-from-column',
        anchor: t('col-tabs-from-column'),
        placement: 'right',
        title: 'Tabs from column…',
        body: 'Choose Tabs from column… in the Column section of the menu.',
        action: true,
        hint: 'Click Tabs from column…',
        advanceOn: { appears: t('create-tabs-dialog') },
        resumeTo: 'open-column-menu',
        missingText: 'Tabs from column… only appears when a saved view is active (tabs are stored on a view). Open the view name menu, pick a saved view or use Save as new view…, and start this guide again.',
      },
      {
        id: 'column',
        anchor: t('create-tabs-column'),
        placement: 'right',
        title: 'Check the column',
        body: 'The column you started from is preselected — pick another one if you like. You get one tab per unique value in the current view, and a warning when that would be more than 10 tabs.',
        resumeTo: 'open-column-menu',
      },
      {
        id: 'color',
        anchor: t('create-tabs-color'),
        placement: 'right',
        title: 'Pick a group color',
        body: 'All tabs created from this column share this color, so you recognise the group in the tab bar.',
        resumeTo: 'open-column-menu',
      },
      {
        id: 'create',
        anchor: t('create-tabs-actions'),
        placement: 'top',
        title: 'Create the tabs',
        body: 'Click Create tabs, or Skip to stop without changes. Values that already have a tab are skipped.',
        action: true,
        hint: 'Click Create tabs or Skip',
        advanceOn: { disappears: true },
      },
      {
        id: 'tab-bar',
        anchor: t('po-view-tab-bar'),
        placement: 'bottom',
        optional: true,
        title: 'Your tab bar',
        body: 'Switch tabs here and hover a tab to see its filters. Filters you set while a tab is active are stored on that tab.',
      },
      {
        id: 'delete-tab',
        anchor: t('po-view-tab-bar'),
        placement: 'bottom',
        optional: true,
        title: 'Delete a tab with right-click',
        bullets: [
          { term: 'This tab only', text: 'removes just the tab you right-clicked' },
          { term: 'All tabs with the same … filter', text: 'removes the whole group created from one column' },
          { term: 'Group color', text: 'changes the color of that group instead' },
        ],
        body: 'Right-click any tab except All. Deleting a tab doesn’t delete any orders — save the view to keep the change.',
      },
      {
        id: 'blank-tab',
        anchor: t('po-view-title'),
        placement: 'bottom',
        title: 'Prefer an empty tab?',
        body: 'Open the view name menu and choose Tab to add a blank tab that you filter yourself.',
      },
      {
        id: 'save',
        anchor: t('po-view-title'),
        placement: 'bottom',
        title: 'Save your changes',
        body: 'A yellow dot next to the view name means unsaved changes. Choose Manage view › Update current view. On a tab you can save for “This tab only” or for “All tabs with the same filter”.',
      },
    ],
  },
];
