import { COLUMN_MENU_MISSING, STAFF, t } from './tourSelectors';


function openColumnMenuStep(body) {
  return {
    id: 'open-column-menu',
    anchor: t('po-column-menu-trigger'),
    reveal: true,
    placement: 'bottom',
    title: 'Open a column menu',
    body,
    action: true,
    hint: 'Click the highlighted … button',
    advanceOn: { appears: t('col-submenu-add') },
    missingText: COLUMN_MENU_MISSING,
  };
}

const addColumnStep = {
  id: 'add-column-right',
  anchor: t('col-submenu-add'),
  placement: 'right',
  title: 'Add column to the right',
  body: 'Hover or click Add column to the right. The list of column types opens next to the menu.',
  action: true,
  hint: 'Hover the highlighted item',
  advanceOn: { appears: t('col-type-list') },
  resumeTo: 'open-column-menu',
  missingText: 'This column doesn’t allow adding columns next to it. Close the menu and try another column header.',
};

/** How-to guides on the Master plan board (staff). */
export const BOARD_GUIDES = [
  {
    id: 'guideAddColumn',
    kind: 'guide',
    version: 1,
    route: '/',
    roles: STAFF,
    icon: 'column',
    title: 'Add a column',
    description: 'Add your own status, text, number, date or remarks column.',
    steps: [
      openColumnMenuStep('New columns are added from the column menu. Hover a column header and click the … button.'),
      addColumnStep,
      {
        id: 'pick-type',
        anchor: t('col-type-list'),
        placement: 'right',
        title: 'Pick a column type',
        bullets: [
          { term: 'Status', text: 'colored labels you define' },
          { term: 'Text, Numbers, Date', text: 'free input per order' },
          { term: 'Yes/No', text: 'a simple check' },
          { term: 'Remarks', text: 'a comment thread per order' },
          { term: 'Formula, Date W/M', text: 'calculated — see their own guides' },
        ],
        body: 'The new column appears to the right with its name ready to edit.',
        action: true,
        hint: 'Click a column type',
        advanceOn: { click: '[data-tour^="col-type-"]:not([data-tour="col-type-list"])' },
        resumeTo: 'open-column-menu',
      },
      {
        id: 'rename',
        anchor: '[data-testid="header-row"] input',
        optional: true,
        placement: 'bottom',
        title: 'Name your column',
        body: 'Type a name in the highlighted header and press Enter. You can rename it later from the same column menu.',
      },
      {
        id: 'hide',
        anchor: t('po-column-menu-trigger'),
        reveal: true,
        placement: 'bottom',
        title: 'Hide or delete',
        body: 'Hide column collapses a column into a narrow stub — click the stub to show it again. Your own columns can be removed with Delete column.',
      },
    ],
  },
  {
    id: 'guideFormula',
    kind: 'guide',
    version: 1,
    route: '/',
    roles: STAFF,
    icon: 'formula',
    title: 'Add a formula column',
    description: 'Calculate values from other columns, like a spreadsheet.',
    steps: [
      openColumnMenuStep('Formula columns are added next to an existing column. Hover a column header and click …'),
      addColumnStep,
      {
        id: 'choose-formula',
        anchor: t('col-type-formula'),
        placement: 'right',
        title: 'Choose Formula',
        body: 'A dialog opens where you write the formula.',
        action: true,
        hint: 'Click Formula',
        advanceOn: { appears: t('formula-dialog') },
        resumeTo: 'open-column-menu',
      },
      {
        id: 'name',
        anchor: t('formula-name'),
        placement: 'right',
        title: 'Name the column',
        body: 'This becomes the column header, for example “Days late”.',
        resumeTo: 'open-column-menu',
      },
      {
        id: 'result-type',
        anchor: t('formula-result-type'),
        placement: 'right',
        title: 'Choose the result type',
        body: 'Number for calculations, Text for labels such as “Too late”, Date for calculated dates and Yes/No for checks. It decides how the column sorts, filters and formats.',
        resumeTo: 'open-column-menu',
      },
      {
        id: 'expression',
        anchor: t('formula-expression'),
        placement: 'right',
        title: 'Write the formula',
        body: 'Refer to columns as (columnKey), separate arguments with a semicolon and put text in single quotes.',
        cheatsheet: [
          ['(columnKey)', 'value of a column'],
          ['IF(test; then; else)', 'condition'],
          ['a AND b · a OR b', 'combine conditions'],
          ['ROUND(n; decimals)', 'round a number'],
          ['ABS(n)', 'absolute value'],
          ['MIN(a; b) · MAX(a; b)', 'smallest · largest'],
          ['TODAY()', 'today’s date'],
          ['NETWORKDAYS(start; end)', 'working days between dates'],
        ],
        example: "IF((a)>(b);'Too late';(a)+(b))",
        resumeTo: 'open-column-menu',
      },
      {
        id: 'help',
        anchor: t('formula-help'),
        placement: 'right',
        title: 'Insert instead of typing',
        body: 'Click a column chip to insert its reference, or a function chip to insert a ready-made snippet.',
        resumeTo: 'open-column-menu',
      },
      {
        id: 'check',
        anchor: t('formula-check'),
        placement: 'right',
        title: 'Check before saving',
        body: 'Check formula validates it and shows a tip when something is off.',
        resumeTo: 'open-column-menu',
      },
      {
        id: 'save',
        anchor: t('formula-actions'),
        placement: 'top',
        title: 'Save or cancel',
        body: 'You can add conditional formatting above. Click Save to add the column, or Cancel — nothing changes until you do.',
        action: true,
        hint: 'Click Save or Cancel to finish',
        advanceOn: { disappears: true },
      },
    ],
  },
  {
    id: 'guideDatePeriod',
    kind: 'guide',
    version: 1,
    route: '/',
    roles: STAFF,
    icon: 'calendar',
    title: 'Week or month column',
    description: 'Show week numbers or month names based on a date column.',
    steps: [
      openColumnMenuStep('Hover a column header and click … — preferably a column on the order header.'),
      addColumnStep,
      {
        id: 'choose-date-period',
        anchor: t('col-type-date_wm'),
        placement: 'right',
        title: 'Choose Date W/M',
        body: 'W/M stands for week or month. It is available for order header columns.',
        action: true,
        hint: 'Click Date W/M',
        advanceOn: { appears: t('date-period-dialog') },
        resumeTo: 'open-column-menu',
        missingText: 'Date W/M is only available on order header columns, not on purchase lines. Close the menu and open it on a header column.',
      },
      {
        id: 'label',
        anchor: t('date-period-label'),
        placement: 'right',
        title: 'Label the column',
        body: 'For example “Delivery week”.',
        resumeTo: 'open-column-menu',
      },
      {
        id: 'source',
        anchor: t('date-period-source'),
        placement: 'right',
        title: 'Pick the source date',
        body: 'Choose the date to derive from, such as the confirmed delivery date. The column follows that date automatically.',
        resumeTo: 'open-column-menu',
      },
      {
        id: 'add',
        anchor: t('date-period-actions'),
        placement: 'top',
        title: 'Add the column',
        body: 'Click Add column, or Cancel to stop without changes.',
        action: true,
        hint: 'Click Add column or Cancel',
        advanceOn: { disappears: true },
      },
      {
        id: 'display-as',
        anchor: '[data-testid="header-row"]',
        placement: 'bottom',
        title: 'Week number or month name',
        body: 'Open the new column’s … menu and pick Week number or Month name under “Display as”. The choice is saved per view.',
      },
    ],
  },
];
