import { STAFF, t } from './tourSelectors';

const VIEW_MENU = t('po-view-menu');
const VIEW_MENU_MISSING = 'The view menu isn’t open. Click the view name above the table and start this guide again.';

function openViewMenuStep(body) {
  return {
    id: 'open-view-menu',
    anchor: t('po-view-title'),
    placement: 'bottom',
    title: 'Open the view menu',
    body,
    action: true,
    hint: 'Click the view name',
    advanceOn: { appears: VIEW_MENU },
    missingText: 'The view name isn’t visible. Open the Master plan board and start this guide again.',
  };
}

/** How-to guides for the view menu on the Master plan board. */
export const VIEW_GUIDES = [
  {
    id: 'guideViewMenu',
    kind: 'guide',
    version: 1,
    route: '/',
    icon: 'view',
    title: 'The view menu',
    description: 'Switch views, choose your default and manage, save and export views.',
    steps: [
      openViewMenuStep('A view remembers filters, sorting, grouping and columns. The big name above the table is the view you are looking at — click it to open the menu.'),
      {
        id: 'views',
        anchor: VIEW_MENU,
        placement: 'right',
        title: 'Pick a view',
        bullets: [
          { term: 'All orders (no view)', text: 'every order, without saved filters' },
          { term: 'Vendor views', text: 'shared with vendors' },
          { term: 'Shared views', text: 'set up for the whole team' },
          { term: 'Personal views', text: 'only you see them' },
        ],
        body: 'The icon in front of the name tells you who sees the view. Click a name to switch.',
        resumeTo: 'open-view-menu',
        missingText: VIEW_MENU_MISSING,
      },
      {
        id: 'default',
        anchor: t('po-view-default'),
        placement: 'right',
        title: 'Your default view',
        body: 'The star behind a name marks the view that opens when you start. Click a grey star to make that view your default — it turns blue. Only one view can be the default; click the blue star to go back to All orders.',
        resumeTo: 'open-view-menu',
        missingText: VIEW_MENU_MISSING,
      },
      {
        id: 'history',
        anchor: t('po-view-history'),
        placement: 'right',
        title: 'History on or off',
        body: 'The clock icon shows changed values in the table for that view. Blue is on, grey is off — click to switch.',
        resumeTo: 'open-view-menu',
        missingText: VIEW_MENU_MISSING,
      },
      {
        id: 'pin',
        anchor: t('po-view-pin'),
        roles: STAFF,
        optional: true,
        placement: 'right',
        title: 'Pin as a tab',
        body: 'The pin puts a view in the bar next to the view name, so you switch with one click.',
        resumeTo: 'open-view-menu',
      },
      {
        id: 'manage',
        anchor: VIEW_MENU,
        roles: STAFF,
        placement: 'right',
        title: 'Manage and save',
        bullets: [
          { term: 'Update current view', text: 'saves your changes — shown when the yellow dot is on' },
          { term: 'Rename…, Delete view', text: 'for the view you are looking at' },
          { term: 'Save as new view…', text: 'keeps the current filters and columns as a new view' },
          { term: 'Tab, Tabs from column…', text: 'add tabs inside a view — see the Create tabs guide' },
        ],
        body: 'Manage view only appears when a saved view is open that you are allowed to change.',
        resumeTo: 'open-view-menu',
        missingText: VIEW_MENU_MISSING,
      },
      {
        id: 'export',
        anchor: VIEW_MENU,
        placement: 'right',
        title: 'Download to Excel',
        body: 'At the bottom of the menu you download the orders of the current view as an Excel file.',
        resumeTo: 'open-view-menu',
        missingText: VIEW_MENU_MISSING,
      },
    ],
  },
  {
    id: 'guidePinView',
    kind: 'guide',
    version: 1,
    route: '/',
    roles: STAFF,
    icon: 'pin',
    title: 'Pin a view',
    description: 'Put your favourite views next to the view name and switch with one click.',
    steps: [
      openViewMenuStep('Views are pinned from the view menu. Click the view name above the table.'),
      {
        id: 'pin',
        anchor: t('po-view-pin'),
        placement: 'right',
        title: 'Click the pin',
        body: 'Every saved view has a pin at the end of its row. A grey pin is not pinned, a blue pin is. All orders can’t be pinned.',
        action: true,
        hint: 'Click a pin',
        advanceOn: { click: t('po-view-pin') },
        resumeTo: 'open-view-menu',
        missingText: 'There are no saved views to pin yet. Use Save as new view… in the view menu first, then start this guide again.',
      },
      {
        id: 'pinned-tabs',
        anchor: t('po-pinned-view-tabs'),
        optional: true,
        placement: 'bottom',
        title: 'Your pinned views',
        body: 'Pinned views appear next to the view name. Click one to switch to it.',
      },
      {
        id: 'arrange',
        anchor: t('po-pinned-view-tabs'),
        optional: true,
        placement: 'bottom',
        title: 'Arrange or unpin',
        bullets: [
          { term: 'Sort A to Z, Sort Z to A', text: 'orders them by name' },
          { term: 'Reorder tabs…', text: 'drag them in your own order — only you see it' },
          { term: 'Unpin', text: 'removes the view from the bar' },
        ],
        body: 'Right-click a pinned view to open these options.',
      },
      {
        id: 'shared',
        anchor: t('po-view-title'),
        placement: 'bottom',
        title: 'Shared views',
        body: 'Pinning a shared or vendor view pins it for everyone who sees that view. Your personal views are only pinned for you.',
      },
    ],
  },
  {
    id: 'guideViewHistory',
    kind: 'guide',
    version: 1,
    route: '/',
    icon: 'history',
    title: 'Show history',
    description: 'Mark changed values in the table and see what changed.',
    steps: [
      openViewMenuStep('History is switched on or off per view. Click the view name above the table.'),
      {
        id: 'toggle',
        anchor: t('po-view-history'),
        placement: 'right',
        title: 'Click the clock',
        body: 'The clock before the pin switches history for that view. Blue means on, grey means off. The setting is saved with the view.',
        action: true,
        hint: 'Click a clock icon',
        advanceOn: { click: t('po-view-history') },
        resumeTo: 'open-view-menu',
        missingText: VIEW_MENU_MISSING,
      },
      {
        id: 'cells',
        anchor: t('po-cell'),
        optional: true,
        placement: 'bottom',
        title: 'Changed values in the table',
        body: 'With history on, cells whose value has changed get a small folded corner. Click the corner to see every change to that value — when, what and by whom.',
      },
      {
        id: 'locked',
        anchor: t('po-view-title'),
        placement: 'bottom',
        title: 'Can’t switch it?',
        body: 'A clock you can’t click belongs to a shared view that only staff can change. All orders and your personal views you can always switch yourself.',
      },
    ],
  },
];
