import { STAFF, t } from './tourSelectors';

/** Guides for conditional formatting and the performance/KPI panel below the board. */
export const INSIGHT_GUIDES = [
  {
    id: 'guideConditionalFormatting',
    kind: 'guide',
    version: 1,
    route: '/',
    roles: STAFF,
    icon: 'paint',
    title: 'Conditional formatting',
    description: 'Color cells or whole rows automatically when a value matches a rule.',
    steps: [
      {
        id: 'open-column-menu',
        anchor: t('po-column-menu-trigger'),
        reveal: true,
        placement: 'bottom',
        title: 'Open a column menu',
        body: 'Formatting rules belong to a column. Hover the header of the column you want to test on and click …',
        action: true,
        hint: 'Click the highlighted … button',
        advanceOn: { appears: t('col-submenu-formatRules') },
        missingText: 'No column menu is visible right now. Open the Master plan board and make sure orders are loaded.',
      },
      {
        id: 'formatting-item',
        anchor: t('col-submenu-formatRules'),
        placement: 'right',
        title: 'Conditional formatting',
        body: 'Hover Conditional formatting. It isn’t available on image and remarks columns.',
        action: true,
        hint: 'Hover the highlighted item',
        advanceOn: { appears: t('format-rules-manage') },
        resumeTo: 'open-column-menu',
        missingText: 'This column can’t be formatted. Close the menu and try another column.',
      },
      {
        id: 'manage',
        anchor: t('format-rules-manage'),
        placement: 'right',
        title: 'Manage formatting rules',
        body: 'The summary above shows how many rules this column has. Click Manage formatting rules to edit them.',
        action: true,
        hint: 'Click Manage formatting rules',
        advanceOn: { appears: t('format-rules-dialog') },
        resumeTo: 'open-column-menu',
      },
      {
        id: 'target',
        anchor: t('format-rules-target'),
        placement: 'right',
        title: 'Cell or row',
        bullets: [
          { term: 'Cell', text: 'colors only this column’s cell' },
          { term: 'Row', text: 'colors the whole order row when a rule matches' },
        ],
        resumeTo: 'open-column-menu',
      },
      {
        id: 'rules',
        anchor: t('format-rules-add'),
        placement: 'right',
        title: 'Add rules',
        body: 'Click + Add rule. Each rule has three parts:',
        bullets: [
          { term: 'Operator', text: '=, !=, >, <, >=, <= or contains' },
          { term: 'Value or Column', text: 'compare with a fixed value or with another column' },
          { term: 'Color', text: 'the fill used when the rule matches' },
        ],
        resumeTo: 'open-column-menu',
      },
      {
        id: 'done',
        anchor: t('format-rules-done'),
        placement: 'top',
        title: 'Done',
        body: 'Click Done to apply the rules. Remove them later with Reset to default in the same menu.',
        action: true,
        hint: 'Click Done to continue',
        advanceOn: { disappears: true },
      },
      {
        id: 'overview',
        anchor: t('po-active-filters'),
        placement: 'right',
        title: 'Keep an overview',
        body: 'Columns with rules get a dashed line under their header. All formatting rules are listed here, next to the active filters.',
      },
    ],
  },
  {
    id: 'guideBoardInsights',
    kind: 'guide',
    version: 1,
    route: '/',
    icon: 'kpi',
    title: 'Performance & KPIs below the table',
    description: 'Open the panel under the board for planning charts and KPI tiles.',
    steps: [
      {
        id: 'open',
        anchor: t('board-split-toggle'),
        placement: 'top',
        title: 'Open the panel',
        body: 'At the bottom of the table sits a panel with performance and KPIs for the orders you are looking at. Click the arrow to open it.',
        action: true,
        hint: 'Click the highlighted arrow',
        advanceOn: { appears: t('board-split-resize') },
      },
      {
        id: 'tabs',
        anchor: t('board-split-tabs'),
        placement: 'top',
        title: 'Two views',
        bullets: [
          { term: 'Performance & Planning', text: 'load versus capacity for the vendor in your current filter' },
          { term: 'KPIs', text: 'totals for the orders in the table' },
        ],
        body: 'Clicking a tab also opens the panel when it is closed.',
      },
      {
        id: 'kpis',
        anchor: t('rccp-kpis'),
        activate: t('board-split-tab-kpis'),
        placement: 'top',
        optional: true,
        title: 'KPI tiles',
        body: 'Values come from the orders currently in the table. Click a tile to filter the table on those orders — quantity columns then show the units counted by that tile. Click the tile again to clear the filter.',
      },
      {
        id: 'performance',
        anchor: t('board-split-bar'),
        activate: t('board-split-tab-rccp'),
        placement: 'top',
        title: 'Performance & Planning',
        body: 'Pick the weeks, week or month view and the load date right in this bar. The chart follows the vendor and items you filter on in the table; click an item in the chart to filter the table on it.',
      },
      {
        id: 'resize',
        anchor: t('board-split-resize'),
        placement: 'top',
        title: 'Make it bigger or smaller',
        body: 'Drag this edge up or down (or focus it and use the arrow keys). Click the arrow to hide the panel again — it remembers how you left it.',
      },
    ],
  },
];
