import { ROLES } from '../../constants/roles';
import { t } from './tourSelectors';

/** How-to guide for the Performance & Planning settings (admins). */
export const RCCP_GUIDES = [
  {
    id: 'guideRccpSettings',
    kind: 'guide',
    version: 1,
    route: '/rccp',
    roles: [ROLES.ADMIN],
    icon: 'settings',
    title: 'Performance & Planning settings',
    description: 'Which columns drive the planning, and how charts look.',
    steps: [
      {
        id: 'intro',
        anchor: t('nav-rccp'),
        placement: 'right',
        title: 'Performance & Planning',
        body: 'This page compares ordered and confirmed load with vendor capacity per week. A few settings decide where those numbers come from.',
      },
      {
        id: 'open-settings',
        anchor: t('rccp-settings-button'),
        placement: 'bottom',
        title: 'Open Settings',
        body: 'Only admins see this button. Changes apply to everyone who uses the page.',
        action: true,
        hint: 'Click Settings',
        advanceOn: { appears: t('rccp-settings-panel') },
      },
      {
        id: 'data',
        anchor: t('rccp-settings-panel'),
        activate: t('rccp-settings-tab-data'),
        placement: 'left',
        title: 'Data — where numbers come from',
        bullets: [
          { term: 'Vendor', text: 'the purchase order column that identifies the vendor' },
          { term: 'Requested delivery date', text: 'places load in a week when there is no confirmed date' },
          { term: 'Confirmed delivery date', text: 'overrides the requested date when filled in' },
          { term: 'Receipt date', text: 'where received quantities are shown' },
          { term: 'Excluded PO statuses', text: 'statuses left out of the load' },
          { term: 'Capacity import', text: 'update or skip duplicate Excel rows' },
        ],
        resumeTo: 'open-settings',
      },
      {
        id: 'quantities',
        anchor: t('rccp-settings-panel'),
        activate: t('rccp-settings-tab-quantities'),
        placement: 'left',
        title: 'Quantities — what is counted',
        bullets: [
          { term: 'Open', text: 'still to be delivered, full color in the chart' },
          { term: 'Received', text: 'already delivered, faded color' },
          { term: 'Ordered', text: 'shown as a matrix row' },
        ],
        body: 'Map each to a number column and set its label, color and whether it shows in the chart. Missing a column? Create a number or formula column on the order header first.',
        resumeTo: 'open-settings',
      },
      {
        id: 'display',
        anchor: t('rccp-settings-panel'),
        activate: t('rccp-settings-tab-display'),
        placement: 'left',
        title: 'Display — how it looks',
        bullets: [
          { term: 'Item picker columns', text: 'extra fields shown in the item dropdown' },
          { term: 'Capacity / warning line', text: 'reference lines in the chart' },
          { term: 'Confirmed bar color', text: 'fill for confirmed load' },
          { term: 'Green % · Orange %', text: 'matrix thresholds; above orange turns red' },
        ],
        resumeTo: 'open-settings',
      },
      {
        id: 'highlights',
        anchor: t('rccp-settings-panel'),
        activate: t('rccp-settings-tab-highlights'),
        placement: 'left',
        title: 'Highlights — mark periods',
        body: 'Switch on “Show on chart” and add week ranges to color periods such as holidays or peak season behind the chart.',
        resumeTo: 'open-settings',
      },
      {
        id: 'save',
        anchor: t('rccp-settings-save'),
        placement: 'top',
        title: 'Save settings',
        body: 'Nothing is stored until you click Save settings. The dashboard then reloads with the new setup.',
        resumeTo: 'open-settings',
      },
    ],
  },
];
