import { t } from './tourSelectors';

/** How-to guides for cell actions and remarks on the Master plan board (all roles). */
export const REMARKS_GUIDES = [
  {
    id: 'guideCellActions',
    kind: 'guide',
    group: 'table',
    version: 1,
    route: '/',
    icon: 'cursor',
    title: 'Right-click a cell',
    description: 'Copy a value, filter on it or open remarks — straight from the table.',
    steps: [
      {
        id: 'right-click',
        anchor: t('po-cell'),
        placement: 'bottom',
        title: 'Right-click any cell',
        body: 'Most cells in the table have a menu with quick actions. Right-click the highlighted cell to open it.',
        action: true,
        hint: 'Right-click the highlighted cell',
        advanceOn: { appears: t('cell-context-menu') },
        missingText: 'No table cells are visible right now. Wait until the orders are loaded and start the guide again.',
      },
      {
        id: 'menu',
        anchor: t('cell-context-menu'),
        placement: 'right',
        title: 'Quick actions',
        bullets: [
          { term: 'Remarks', text: 'open the remarks of this order, linked to this column' },
          { term: 'Filter column on this cell', text: 'show only rows with this value' },
          { term: 'Clear column filter', text: 'appears when the column is already filtered' },
          { term: 'Copy cell value', text: 'copies the value to your clipboard' },
        ],
        body: 'Image and remarks cells only offer Remarks.',
        action: true,
        hint: 'Pick an option — try Filter column on this cell',
        advanceOn: { click: '[data-tour="cell-context-menu"] [role="menuitem"]' },
        resumeTo: 'right-click',
      },
      {
        id: 'undo',
        anchor: t('po-active-filters'),
        placement: 'right',
        title: 'Undo a filter',
        body: 'Right-click a cell in the same column and choose Clear column filter, or open the active filters here to see and clear everything at once.',
      },
    ],
  },
  {
    id: 'guideRemarks',
    kind: 'guide',
    group: 'remarks',
    version: 1,
    route: '/',
    icon: 'remarks',
    title: 'Place a remark',
    description: 'Start a conversation on an order and see its change history.',
    steps: [
      {
        id: 'open-remarks',
        anchor: t('row-remarks-badge'),
        placement: 'right',
        title: 'Open the remarks of an order',
        body: 'Every row starts with a speech bubble. A + means there are no remarks yet; a number shows how many there are. Tip: right-click a cell and choose Remarks to link your remark to that column.',
        action: true,
        hint: 'Click the highlighted speech bubble',
        advanceOn: { appears: t('remarks-panel') },
        missingText: 'No order rows are visible right now. Wait until the orders are loaded and start the guide again.',
      },
      {
        id: 'tabs',
        anchor: t('remarks-tabs'),
        placement: 'left',
        title: 'Remarks, History and All',
        body: 'Remarks is the conversation about this order. History lists every change to its values. All combines both in one timeline.',
        resumeTo: 'open-remarks',
      },
      {
        id: 'compose',
        anchor: t('remark-composer'),
        placement: 'left',
        title: 'Write your remark',
        body: 'Type your message (up to 2,000 characters) and click Add remark. When you opened the panel from a cell, the remark is linked to that column.',
        resumeTo: 'open-remarks',
      },
      {
        id: 'feed',
        anchor: t('remarks-panel'),
        placement: 'left',
        title: 'The conversation',
        body: 'Remarks appear below the editor with name and time, and you can react to them. The order number at the top takes you back to the order in the table. Close the panel with the X.',
        resumeTo: 'open-remarks',
      },
    ],
  },
];
