import { COLUMN_MENU_SURFACE, t } from './tourSelectors';

const REMARKS_COLUMN_TRIGGER = '[data-tour="po-column-menu-trigger"][data-column-type="remarks"]';

/** How-to guides for cell actions and remarks on the Master plan board (all roles). */
export const REMARKS_GUIDES = [
  {
    id: 'guideCellActions',
    kind: 'guide',
    version: 1,
    route: '/',
    icon: 'cursor',
    title: 'Right-click a cell',
    description: 'Copy a value, filter on it or open remarks — straight from the table.',
    steps: [
      {
        id: 'right-click',
        anchor: t('po-cell'),
        placement: 'bottom',
        title: 'Right-click any cell',
        body: 'Most cells in the table have a menu with quick actions. Right-click the highlighted cell to open it.',
        action: true,
        hint: 'Right-click the highlighted cell',
        advanceOn: { appears: t('cell-context-menu') },
        missingText: 'No table cells are visible right now. Wait until the orders are loaded and start the guide again.',
      },
      {
        id: 'menu',
        anchor: t('cell-context-menu'),
        placement: 'right',
        title: 'Quick actions',
        bullets: [
          { term: 'Remarks', text: 'open the remarks of this order, linked to this column' },
          { term: 'Filter column on this cell', text: 'show only rows with this value' },
          { term: 'Clear column filter', text: 'appears when the column is already filtered' },
          { term: 'Copy cell value', text: 'copies the value to your clipboard' },
        ],
        body: 'Image and remarks cells only offer Remarks.',
        action: true,
        hint: 'Pick an option — try Filter column on this cell',
        advanceOn: { click: '[data-tour="cell-context-menu"] [role="menuitem"]' },
        resumeTo: 'right-click',
      },
      {
        id: 'undo',
        anchor: t('po-active-filters'),
        placement: 'right',
        title: 'Undo a filter',
        body: 'Right-click a cell in the same column and choose Clear column filter, or open the active filters here to see and clear everything at once.',
      },
    ],
  },
  {
    id: 'guideRemarks',
    kind: 'guide',
    version: 1,
    route: '/',
    icon: 'remarks',
    title: 'Place a remark',
    description: 'Start a conversation on an order and see its change history.',
    steps: [
      {
        id: 'open-remarks',
        anchor: t('row-remarks-badge'),
        placement: 'right',
        title: 'Open the remarks of an order',
        body: 'Every row starts with a speech bubble. A + means there are no remarks yet; a number shows how many there are. Tip: right-click a cell and choose Remarks to link your remark to that column.',
        action: true,
        hint: 'Click the highlighted speech bubble',
        advanceOn: { appears: t('remarks-panel') },
        missingText: 'No order rows are visible right now. Wait until the orders are loaded and start the guide again.',
      },
      {
        id: 'tabs',
        anchor: t('remarks-tabs'),
        placement: 'left',
        title: 'Remarks, History and All',
        body: 'Remarks is the conversation about this order. History lists every change to its values. All combines both in one timeline.',
        resumeTo: 'open-remarks',
      },
      {
        id: 'compose',
        anchor: t('remark-composer'),
        placement: 'left',
        title: 'Write your remark',
        body: 'Type your message (up to 2,000 characters) and click Add remark. When you opened the panel from a cell, the remark is linked to that column.',
        resumeTo: 'open-remarks',
      },
      {
        id: 'feed',
        anchor: t('remarks-panel'),
        placement: 'left',
        title: 'The conversation',
        body: 'Remarks appear below the editor with name and time, and you can react to them. The order number at the top takes you back to the order in the table. Close the panel with the X.',
        resumeTo: 'open-remarks',
      },
    ],
  },
  {
    id: 'guideRemarksColumn',
    kind: 'guide',
    version: 1,
    route: '/',
    icon: 'remarks',
    title: 'The Remarks column',
    description: 'See the latest remark per order and filter on remarks.',
    steps: [
      {
        id: 'column',
        anchor: t('remarks-latest-cell'),
        placement: 'bottom',
        title: 'Latest remark at a glance',
        body: 'The Remarks column shows the most recent remark of each order; hover it to see who wrote it and when. “No remarks” means the conversation is still empty. Click a cell to open all remarks.',
        missingText: 'This view has no Remarks column yet. Staff can add one: open a column menu (…) › Add column to the right › Remarks.',
      },
      {
        id: 'open-filter',
        anchor: REMARKS_COLUMN_TRIGGER,
        reveal: true,
        placement: 'bottom',
        title: 'Filter on remarks',
        body: 'Open the menu of the Remarks column to filter orders by their remarks.',
        action: true,
        hint: 'Click the highlighted … button',
        advanceOn: { appears: COLUMN_MENU_SURFACE },
        optional: true,
      },
      {
        id: 'filter-options',
        anchor: COLUMN_MENU_SURFACE,
        placement: 'right',
        title: 'Two ways to filter',
        bullets: [
          { term: 'contains', text: 'orders whose remarks include a word (2–200 characters)' },
          { term: 'has a comment', text: 'only orders with at least one remark' },
        ],
        body: 'Choose an operator, fill in a value if needed and click Apply.',
        action: true,
        hint: 'Click Apply, or press Esc to close the menu',
        advanceOn: { disappears: true },
        optional: true,
      },
      {
        id: 'clear',
        anchor: t('po-active-filters'),
        placement: 'right',
        title: 'Clear it again',
        body: 'Active remark filters are listed here together with all other filters, so you can clear them in one place.',
      },
    ],
  },
];
