import { ROLES } from '../../constants/roles';
import { t } from './tourSelectors';

/** Orientation tours — one per page, offered on first visit. */
export const PAGE_TOURS = [
  {
    id: 'poBoard',
    kind: 'tour',
    version: 1,
    route: '/',
    icon: 'board',
    title: 'Master plan tour',
    description: 'Views, column menus, filters and where to find help.',
    steps: [
      {
        id: 'nav',
        anchor: t('nav-rail'),
        placement: 'right',
        title: 'Find your way',
        body: 'Switch between the Master plan (purchase orders) and Performance & Planning here. Settings sits at the bottom.',
      },
      {
        id: 'views',
        anchor: t('po-view-title'),
        placement: 'bottom',
        title: 'Views',
        body: 'Click the view name to switch between saved views, save your own filtered layout and export to Excel.',
      },
      {
        id: 'tabs',
        anchor: t('po-view-tab-bar'),
        placement: 'bottom',
        optional: true,
        title: 'Tabs',
        body: 'A view can have tabs, each with its own filters. Hover a tab to see what it filters on; right-click a tab to delete it.',
      },
      {
        id: 'column-menu',
        anchor: t('po-column-menu-trigger'),
        reveal: true,
        placement: 'bottom',
        title: 'Column menu',
        body: 'Hover any column header and click … to sort, filter, group and style that column.',
      },
      {
        id: 'cell-menu',
        anchor: t('po-cell'),
        placement: 'bottom',
        optional: true,
        title: 'Right-click a cell',
        body: 'Right-click any cell to copy its value, filter the column on it or open the remarks of that order.',
      },
      {
        id: 'remarks',
        anchor: t('row-remarks-badge'),
        placement: 'right',
        optional: true,
        title: 'Remarks',
        body: 'The speech bubble at the start of each row opens the remarks and change history of that order. A number shows how many remarks there are.',
      },
      {
        id: 'table-options',
        anchor: t('po-table-options'),
        placement: 'right',
        title: 'Expand and collapse',
        body: 'Expand orders to see their purchase lines, or collapse everything again in one click.',
      },
      {
        id: 'active-filters',
        anchor: t('po-active-filters'),
        placement: 'right',
        optional: true,
        title: 'Active filters',
        body: 'See every active filter and formatting rule in one place, and clear them when you need a fresh start.',
      },
      {
        id: 'bottom-panel',
        anchor: t('board-split-bar'),
        placement: 'top',
        optional: true,
        title: 'Performance & KPIs',
        body: 'Below the table you can open a panel with planning charts and KPI tiles for the orders in view. Click the arrow or a tab to open it.',
      },
      {
        id: 'vendor',
        anchor: t('header-vendor'),
        roles: [ROLES.SUPPLIER],
        optional: true,
        placement: 'bottom',
        title: 'Your orders only',
        body: 'You’re signed in for this vendor, so the board only shows its orders.',
      },
      {
        id: 'guides',
        anchor: t('header-guides'),
        placement: 'bottom',
        title: 'Help is always here',
        body: 'Open Guides for step-by-step walkthroughs, or replay this tour at any time.',
      },
    ],
  },
  {
    id: 'rccp',
    kind: 'tour',
    version: 1,
    route: '/rccp',
    icon: 'chart',
    title: 'Performance & Planning tour',
    description: 'Dashboard, filters, KPIs and capacity planning.',
    steps: [
      {
        id: 'tabs',
        anchor: t('rccp-tabs'),
        placement: 'bottom',
        title: 'Dashboard and capacity planning',
        body: 'Dashboard compares ordered and confirmed load with capacity per week. Capacity planning shows the weekly capacity itself.',
      },
      {
        id: 'toolbar',
        anchor: t('rccp-toolbar'),
        placement: 'bottom',
        title: 'Choose what you look at',
        body: 'Pick a vendor, narrow down to items and set the weeks. Refresh reloads the latest data.',
      },
      {
        id: 'period',
        anchor: t('rccp-week-picker'),
        placement: 'bottom',
        optional: true,
        title: 'Select weeks',
        body: 'Click Period to open the week calendar. Click the first week, then the last week of the range. Tip: click a week twice to lock it, then pick the other end. Now jumps to the current week; Clear all starts a fresh selection.',
      },
      {
        id: 'data-weeks',
        anchor: t('rccp-show-data-weeks'),
        activate: t('rccp-week-picker'),
        placement: 'right',
        optional: true,
        title: 'Show weeks with data',
        body: 'One click selects exactly the weeks in which this vendor has order load, so you never look at an empty chart. The button is disabled when the vendor has no load. If your weeks turn out empty, the page offers the same button.',
      },
      {
        id: 'kpi-window',
        anchor: t('rccp-kpi-window-switch'),
        placement: 'bottom',
        optional: true,
        title: 'KPIs in selected weeks',
        body: 'Switch on to calculate the KPI cards for the selected weeks only; switch off to include all load of the vendor.',
      },
      {
        id: 'view-grain',
        anchor: t('rccp-view-grain'),
        placement: 'bottom',
        optional: true,
        title: 'View: week or month',
        body: 'Choose whether the chart and the matrix show the load per week or per month.',
      },
      {
        id: 'load-date',
        anchor: t('rccp-load-date'),
        placement: 'bottom',
        optional: true,
        title: 'Load date: requested or confirmed',
        bullets: [
          { term: 'Req.', text: 'shows load on the requested delivery date' },
          { term: 'Confirmed', text: 'shows load on the confirmed delivery date (with the share of confirmed orders)' },
        ],
        body: 'Switch on one or both: with both on, the chart and matrix show both series side by side.',
      },
      {
        id: 'kpis',
        anchor: t('rccp-kpis'),
        placement: 'bottom',
        optional: true,
        title: 'KPIs at a glance',
        body: 'Each card summarises the selected period. Open a card’s formula to see exactly how it is calculated.',
      },
      {
        id: 'settings',
        anchor: t('rccp-settings-button'),
        roles: [ROLES.ADMIN],
        placement: 'bottom',
        title: 'Settings',
        body: 'Admins configure here which purchase order columns drive the planning and how the charts look.',
      },
    ],
  },
];
