import { makeStyles, shorthands, tokens } from '@fluentui/react-components';
import { motion, tourLayers } from '../../styles/motionTokens';
import { enterAnimation, keyframes, reducedMotion } from './onboardingMotion';

export const CARD_WIDTH = 340;

export const useTourCardStyles = makeStyles({
  // Positioned wrapper (moves between steps, shakes on nudge); the surface inside carries visuals.
  card: {
    position: 'fixed',
    zIndex: tourLayers.card,
    width: `${CARD_WIDTH}px`,
    maxWidth: 'calc(100vw - 24px)',
    transitionProperty: 'top, left',
    transitionDuration: `${motion.durationSlow}ms`,
    transitionTimingFunction: motion.easeOut,
    outlineStyle: 'none',
    ...reducedMotion,
  },
  surface: {
    position: 'relative',
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    borderRadius: tokens.borderRadiusXLarge,
    boxShadow: tokens.shadow28,
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
    ...enterAnimation(keyframes.cardIn),
  },
  nudge: {
    animationName: keyframes.nudge,
    animationDuration: '380ms',
    animationTimingFunction: motion.easeStandard,
    ...reducedMotion,
  },
  accent: {
    height: '4px',
    borderTopLeftRadius: tokens.borderRadiusXLarge,
    borderTopRightRadius: tokens.borderRadiusXLarge,
    backgroundImage: `linear-gradient(90deg, ${tokens.colorBrandBackground}, ${tokens.colorBrandBackground2Hover}, ${tokens.colorPaletteMarigoldBorderActive})`,
  },
  inner: { ...shorthands.padding('14px', '16px', '14px') },
  eyebrowRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...shorthands.gap('8px'),
    marginBottom: '6px',
  },
  eyebrow: {
    color: tokens.colorBrandForeground1,
    fontSize: tokens.fontSizeBase100,
    fontWeight: tokens.fontWeightSemibold,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  content: {
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('8px'),
    ...enterAnimation(keyframes.contentIn, motion.durationNormal),
  },
  title: {
    fontSize: tokens.fontSizeBase400,
    lineHeight: tokens.lineHeightBase400,
    fontWeight: tokens.fontWeightSemibold,
  },
  body: { color: tokens.colorNeutralForeground2, lineHeight: tokens.lineHeightBase300 },
  bullets: {
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('4px'),
    ...shorthands.margin(0),
    ...shorthands.padding(0),
    listStyleType: 'none',
  },
  bullet: {
    display: 'grid',
    gridTemplateColumns: '6px 1fr',
    columnGap: '8px',
    alignItems: 'baseline',
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground2,
    '::before': {
      content: '""',
      width: '6px',
      height: '6px',
      borderRadius: '50%',
      backgroundColor: tokens.colorBrandBackground,
      transform: 'translateY(-1px)',
    },
  },
  term: { color: tokens.colorNeutralForeground1, fontWeight: tokens.fontWeightSemibold },
  cheatsheet: {
    display: 'grid',
    gridTemplateColumns: 'auto 1fr',
    columnGap: '10px',
    rowGap: '4px',
    alignItems: 'center',
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground2,
  },
  code: {
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase200,
    backgroundColor: tokens.colorNeutralBackground3,
    color: tokens.colorNeutralForeground1,
    borderRadius: tokens.borderRadiusMedium,
    ...shorthands.padding('1px', '6px'),
    whiteSpace: 'nowrap',
  },
  example: {
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase200,
    backgroundColor: tokens.colorBrandBackground2,
    color: tokens.colorBrandForeground2,
    borderRadius: tokens.borderRadiusMedium,
    ...shorthands.padding('6px', '8px'),
    overflowX: 'auto',
    whiteSpace: 'nowrap',
  },
  hint: {
    display: 'inline-flex',
    alignItems: 'center',
    alignSelf: 'flex-start',
    ...shorthands.gap('8px'),
    ...shorthands.padding('4px', '10px'),
    borderRadius: tokens.borderRadiusCircular,
    backgroundColor: tokens.colorBrandBackground2,
    color: tokens.colorBrandForeground2,
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightSemibold,
  },
  hintDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: tokens.colorBrandBackground,
    animationName: keyframes.hintDot,
    animationDuration: '1.4s',
    animationIterationCount: 'infinite',
    ...reducedMotion,
  },
  footer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...shorthands.gap('8px'),
    marginTop: '14px',
  },
  progress: { display: 'flex', alignItems: 'center', ...shorthands.gap('8px'), minWidth: 0 },
  dots: { display: 'flex', alignItems: 'center', ...shorthands.gap('4px') },
  dot: {
    height: '6px',
    width: '6px',
    borderRadius: tokens.borderRadiusCircular,
    backgroundColor: tokens.colorNeutralStroke1,
    transitionProperty: 'width, background-color',
    transitionDuration: `${motion.durationNormal}ms`,
    transitionTimingFunction: motion.easeOut,
    ...reducedMotion,
  },
  dotDone: { backgroundColor: tokens.colorBrandStroke2 },
  dotActive: { width: '18px', backgroundColor: tokens.colorBrandBackground },
  counter: { color: tokens.colorNeutralForeground3, fontSize: tokens.fontSizeBase200, whiteSpace: 'nowrap' },
  actions: { display: 'flex', alignItems: 'center', ...shorthands.gap('6px') },
  arrow: {
    position: 'absolute',
    width: '12px',
    height: '12px',
    backgroundColor: tokens.colorNeutralBackground1,
    transform: 'rotate(45deg)',
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
  },
  arrowBottom: { top: '-7px', borderRightStyle: 'none', borderBottomStyle: 'none' },
  arrowTop: { bottom: '-7px', borderLeftStyle: 'none', borderTopStyle: 'none' },
  arrowRight: { left: '-7px', borderTopStyle: 'none', borderRightStyle: 'none' },
  arrowLeft: { right: '-7px', borderBottomStyle: 'none', borderLeftStyle: 'none' },
});
